# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ib4TybD6_t93Y1gNhE24Cm7l9_rv8tKj
"""

import cv2
import numpy as np
import streamlit as st

from fingerprint_pipeline import (
    process_fingerprint,
    match_fingerprints
)


st.set_page_config(
    page_title="Fingerprint Recognition Demo",
    page_icon="🖐️",
    layout="wide"
)


@st.cache_data(show_spinner=False)
def decode_uploaded_image(file_bytes: bytes) -> np.ndarray:
    array = np.frombuffer(file_bytes, dtype=np.uint8)

    image = cv2.imdecode(
        array,
        cv2.IMREAD_GRAYSCALE
    )

    if image is None:
        raise ValueError("Không thể giải mã ảnh.")

    return image


@st.cache_data(show_spinner=False)
def run_pipeline(file_bytes: bytes):
    image = decode_uploaded_image(file_bytes)
    return process_fingerprint(image)


def normalize_for_display(image):
    array = np.asarray(image)

    if array.dtype == np.uint8:
        return array

    finite = np.isfinite(array)
    if not finite.any():
        return np.zeros(array.shape, dtype=np.uint8)

    min_value = array[finite].min()
    max_value = array[finite].max()

    if max_value == min_value:
        return np.zeros(array.shape, dtype=np.uint8)

    scaled = (
        (array - min_value)
        / (max_value - min_value)
        * 255
    )

    return np.clip(scaled, 0, 255).astype(np.uint8)


def show_pipeline(result, prefix):
    tab_names = [
        "Ảnh gốc",
        "Chuẩn hóa",
        "Mask",
        "Hướng ridge",
        "Tần số",
        "Gabor",
        "Nhị phân",
        "Skeleton",
        "Pruning"
    ]

    tabs = st.tabs(tab_names)

    with tabs[0]:
        st.image(
            result.original,
            caption=f"{prefix}: Ảnh gốc",
            width="stretch"
        )

    with tabs[1]:
        st.image(
            normalize_for_display(result.normalized),
            caption="Ảnh sau chuẩn hóa",
            width="stretch"
        )

    with tabs[2]:
        st.image(
            normalize_for_display(result.mask),
            caption="Mask vùng vân tay",
            width="stretch"
        )

    with tabs[3]:
        st.image(
            normalize_for_display(result.orientation),
            caption="Ma trận hướng ridge",
            width="stretch"
        )

    with tabs[4]:
        st.image(
            normalize_for_display(result.frequency),
            caption="Ma trận tần số ridge",
            width="stretch"
        )

    with tabs[5]:
        st.image(
            normalize_for_display(result.gabor),
            caption="Ảnh sau lọc Gabor",
            width="stretch"
        )

    with tabs[6]:
        st.image(
            normalize_for_display(result.binary),
            caption="Ảnh nhị phân",
            width="stretch"
        )

    with tabs[7]:
        st.image(
            normalize_for_display(result.skeleton),
            caption="Skeleton",
            width="stretch"
        )

    with tabs[8]:
        st.image(
            normalize_for_display(result.pruned),
            caption="Skeleton sau pruning",
            width="stretch"
        )

    st.metric(
        "Số minutiae/core được phát hiện",
        len(result.minutiae)
    )


st.title("Fingerprint Recognition Demo")

st.markdown(
    """
Ứng dụng minh họa quy trình nhận dạng vân tay dựa trên
**xử lý ảnh truyền thống**:

`Segmentation → Orientation → Frequency → Gabor → Binarization → Skeleton → Minutiae → Matching`
"""
)

with st.sidebar:
    st.header("Cấu hình")

    threshold = st.number_input(
        "Ngưỡng khoảng cách",
        min_value=0.0,
        value=1.0,
        step=0.05,
        help="Ngưỡng phải được hiệu chỉnh bằng dữ liệu thử nghiệm."
    )

    st.warning(
        "Kết quả chỉ phục vụ học tập và nghiên cứu, "
        "không dùng cho xác thực sinh trắc học thực tế."
    )


col_a, col_b = st.columns(2)

with col_a:
    file_a = st.file_uploader(
        "Tải ảnh vân tay A",
        type=["png", "jpg", "jpeg", "bmp"],
        key="fingerprint_a",
        max_upload_size=10
    )

with col_b:
    file_b = st.file_uploader(
        "Tải ảnh vân tay B",
        type=["png", "jpg", "jpeg", "bmp"],
        key="fingerprint_b",
        max_upload_size=10
    )


if file_a is not None:
    try:
        with st.spinner("Đang xử lý ảnh A..."):
            result_a = run_pipeline(file_a.getvalue())

        st.subheader("Quy trình xử lý ảnh A")
        show_pipeline(result_a, "Ảnh A")

    except Exception as exc:
        st.error(f"Lỗi xử lý ảnh A: {exc}")
        result_a = None
else:
    result_a = None


if file_b is not None:
    try:
        with st.spinner("Đang xử lý ảnh B..."):
            result_b = run_pipeline(file_b.getvalue())

        st.subheader("Quy trình xử lý ảnh B")
        show_pipeline(result_b, "Ảnh B")

    except Exception as exc:
        st.error(f"Lỗi xử lý ảnh B: {exc}")
        result_b = None
else:
    result_b = None


if result_a is not None and result_b is not None:
    st.divider()
    st.header("Kết quả đối sánh")

    try:
        match = match_fingerprints(
            result_a,
            result_b,
            threshold=threshold
        )

        metric_1, metric_2, metric_3 = st.columns(3)

        metric_1.metric(
            "Radial distance",
            f"{match.radial_distance:.4f}"
        )

        metric_2.metric(
            "Circular distance",
            f"{match.circular_distance:.4f}"
        )

        metric_3.metric(
            "Tổng khoảng cách",
            f"{match.total_distance:.4f}"
        )

        st.progress(
            min(max(match.similarity, 0.0), 1.0),
            text=f"Similarity quy đổi: {match.similarity:.2%}"
        )

        if match.is_match:
            st.success(
                "Kết quả thử nghiệm: Hai ảnh có khả năng thuộc cùng một ngón."
            )
        else:
            st.error(
                "Kết quả thử nghiệm: Hai ảnh có khả năng thuộc hai ngón khác nhau."
            )

        st.caption(
            "Similarity chỉ là giá trị quy đổi để trực quan hóa, "
            "không phải xác suất sinh trắc học."
        )

    except Exception as exc:
        st.error(f"Không thể đối sánh hai ảnh: {exc}")