# -*- coding: utf-8 -*-
"""fingerprint_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAv3mbbkKk82vYehflhDz2Tf6GNregk6
"""

from dataclasses import dataclass
from typing import Any

import numpy as np

import fplib.binarize as fpbinarize
import fplib.feature as fpfeature
import fplib.filter as fpfilter
import fplib.minutae as fpminutae
import fplib.preprocess as fppreprocess


@dataclass
class FingerprintResult:
    original: np.ndarray
    resized: np.ndarray
    normalized: np.ndarray
    mask: np.ndarray
    standardized: np.ndarray
    orientation: np.ndarray
    frequency: np.ndarray
    gabor: np.ndarray
    binary: np.ndarray
    skeleton: np.ndarray
    pruned: np.ndarray
    minutiae: Any
    radial_feature: Any
    circular_feature: Any


def ensure_grayscale(image: np.ndarray) -> np.ndarray:
    if image is None:
        raise ValueError("Không đọc được ảnh.")

    if image.ndim == 2:
        return image

    if image.ndim == 3:
        # Dùng công thức luminance, tránh phụ thuộc thứ tự RGB/BGR.
        image = image.astype(np.float32)
        gray = (
            0.299 * image[:, :, 0]
            + 0.587 * image[:, :, 1]
            + 0.114 * image[:, :, 2]
        )
        return np.clip(gray, 0, 255).astype(np.uint8)

    raise ValueError("Ảnh phải có 2 hoặc 3 chiều.")


def prune_skeleton(skeleton: np.ndarray) -> np.ndarray:
    pattern_1 = np.array([
        [[1, 0, 0], [0, 1, 0], [0, 0, 0]],
        [[0, 1, 0], [0, 1, 0], [0, 0, 0]],
        [[0, 0, 1], [0, 1, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 1, 1], [0, 0, 0]],
        [[0, 0, 0], [0, 1, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
        [[0, 0, 0], [0, 1, 0], [0, 1, 0]],
        [[0, 0, 0], [0, 1, 0], [1, 0, 0]],
        [[0, 0, 0], [1, 1, 0], [0, 0, 0]]
    ])

    pattern_2 = np.array([
        [[1, 1, 0], [0, 1, 0], [0, 0, 0]],
        [[0, 1, 1], [0, 1, 0], [0, 0, 0]],
        [[0, 0, 1], [0, 1, 1], [0, 0, 0]],
        [[0, 0, 0], [0, 1, 1], [0, 0, 1]],
        [[0, 0, 0], [0, 1, 0], [0, 1, 1]],
        [[0, 0, 0], [0, 1, 0], [1, 1, 0]],
        [[0, 0, 0], [1, 1, 0], [1, 0, 0]],
        [[1, 0, 0], [0, 1, 0], [1, 0, 0]]
    ])

    pattern_3 = np.array([
        [[1, 1, 1], [0, 1, 0], [0, 0, 0]],
        [[0, 0, 1], [0, 1, 1], [0, 0, 1]],
        [[0, 0, 0], [0, 1, 0], [1, 1, 1]],
        [[1, 0, 0], [1, 1, 0], [1, 0, 0]]
    ])

    result = fppreprocess.prune(skeleton, pattern_1, 8)
    result = fppreprocess.prune(result, pattern_2, 1)
    result = fppreprocess.prune(result, pattern_3, 1)

    return result


def process_fingerprint(image: np.ndarray) -> FingerprintResult:
    original = ensure_grayscale(image)

    resized = fppreprocess.resize(
        original,
        width=400,
        height=500
    )

    normalized = fppreprocess.normalize(
        resized,
        low=0,
        upp=255
    )

    mask = fppreprocess.mask(
        normalized,
        blksize=20
    )

    standardized = fppreprocess.standartize(normalized)

    orientation = fppreprocess.orientation(
        standardized,
        grdsigma=3,
        blksigma=3,
        smtsigma=3
    )

    frequency = fppreprocess.frequency(
        standardized,
        orientation,
        blksize=50
    )
    frequency = frequency * mask

    gabor = fpfilter.medgabor(
        standardized,
        orientation,
        frequency
    )

    enhanced_uint8 = 255 - fppreprocess.normalize(
        gabor,
        0,
        255,
        np.uint8
    )

    binary = fpbinarize.binarize(
        enhanced_uint8,
        "otsu"
    )
    binary = fppreprocess.fillholes(binary)

    skeleton = fppreprocess.skeleton(binary)
    pruned = prune_skeleton(skeleton)

    minutiae = fpminutae.minutae(
        pruned,
        orientation,
        remove_invalid=1
    )

    minutiae = np.resize(
        minutiae,
        (minutiae.shape[0] + 1,)
    )

    minutiae[-1] = fpminutae.core(
        orientation,
        mask
    )

    radial_feature = fpfeature.extract(
        minutiae,
        method="radial",
        bucketsize=36
    )

    circular_feature = fpfeature.extract(
        minutiae,
        method="circular",
        bucketsize=30
    )

    return FingerprintResult(
        original=original,
        resized=resized,
        normalized=normalized,
        mask=mask,
        standardized=standardized,
        orientation=orientation,
        frequency=frequency,
        gabor=gabor,
        binary=binary,
        skeleton=skeleton,
        pruned=pruned,
        minutiae=minutiae,
        radial_feature=radial_feature,
        circular_feature=circular_feature
    )

@dataclass
class MatchResult:
    radial_distance: float
    circular_distance: float
    total_distance: float
    similarity: float
    threshold: float
    is_match: bool


def match_fingerprints(
    result_a: FingerprintResult,
    result_b: FingerprintResult,
    threshold: float
) -> MatchResult:
    radial_distance = float(
        fpfeature.distance(
            result_a.radial_feature,
            result_b.radial_feature
        )
    )

    circular_distance = float(
        fpfeature.distance(
            result_a.circular_feature,
            result_b.circular_feature
        )
    )

    total_distance = radial_distance + circular_distance

    # Chỉ là phép quy đổi phục vụ trực quan.
    # Không phải xác suất sinh trắc học.
    similarity = 1.0 / (1.0 + max(total_distance, 0.0))

    return MatchResult(
        radial_distance=radial_distance,
        circular_distance=circular_distance,
        total_distance=total_distance,
        similarity=similarity,
        threshold=threshold,
        is_match=total_distance <= threshold
    )